[package]
name = "mokabench"
version = "0.1.0"
authors = ["Tatsuya Kawano <tatsuya@hibaridb.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.4"
itertools = "0.9"
moka = { git = "https://github.com/moka-rs/moka" }
# moka = { path = "../moka" }
parking_lot = "0.10"
