[package]
name = "mokabench"
version = "0.8.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["moka-v010"]

moka-v010 = ["moka010"]
moka-v09 = ["moka09"]
moka-v08 = ["moka08"]
hashlink = ["dep:hashlink"]
mini-moka = ["dep:mini-moka"]
quick_cache = ["dep:quick_cache"]
stretto = ["dep:stretto"]

[dependencies]
anyhow = "1.0.56"
async-io = "1.12.0"
async-trait = "0.1.64"
clap = "3.2.23"
crossbeam-channel = "0.5.6"
futures-util = "0.3.26"
itertools = "0.10.5"
parking_lot = "0.12.1"
thiserror = "1.0.38"
xxhash-rust = { version = "0.8.6", features = ["xxh3"] }

# Async Runtime
tokio = { version = "1.25.0", features = ["rt-multi-thread", "macros" ] }

# Cache implementations
hashlink = { optional = true, version = "0.8.1" }
mini-moka = { optional = true, version = "0.10.0" }
quick_cache = { optional = true, version = "0.1.0" }
stretto = { optional = true, version = "0.7.1" }

[dependencies.moka010]
package = "moka"
optional = true
# version = "0.10.0"
git = "https://github.com/moka-rs/moka"
branch = "master"
features = ["future"]

[dependencies.moka09]
package = "moka"
optional = true
version = "0.9.7"
features = ["future", "dash"]

[dependencies.moka08]
package = "moka"
optional = true
version = "0.8.6"
features = ["future", "dash"]

[profile.release]
debug=true
# debug-assertions=true
# overflow-checks = true
