[package]
name = "mokabench"
version = "0.1.0"
authors = ["Tatsuya Kawano <tatsuya@hibaridb.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.4"
itertools = "0.9"
# moka = { version = "0.1", path = "../moka" }
moka = "0.1.0-beta.2"
parking_lot = "0.10"
