[package]
name = "mokabench"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
async-io = "1.6.0"
async-trait = "0.1.53"
clap = "3.1.8"
crossbeam-channel = "0.5.4"
fnv = "1.0.7"
futures-util = "0.3.2"
itertools = "0.10.3"
parking_lot = "0.12.0"
thiserror = "1.0.30"

# moka = { version = "0.8.2", features = ["future", "dash"] }
moka = { git = "https://github.com/moka-rs/moka", branch = "master", features = ["future", "dash"] }
# moka = { path = "../moka", features = ["future", "dash"] }

# actix-rt = "2"
# actix-rt = "1"
# async-std = "1"
tokio = { version = "1.17.0", features = ["rt-multi-thread", "macros" ] }
